context:
  version: 2.1.0

package:
  name: voyager
  version: ${{ version }}

source:
  - url: https://github.com/spotify/voyager/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 5f8d687f310b67e9661bb6226b68eea4c8d0c5d48f5866be11c8a37884ce6ed1

build:
  number: 0
  script:
    - cd python
    - ${{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - numpy
        - pybind11
        - setuptools
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - pybind11
    - setuptools
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - voyager
      pip_check: true

about:
  homepage: https://github.com/spotify/voyager
  summary: An approximate nearest-neighbor search library for Python and Java with a focus on ease of use, simplicity, and deployability.
  documentation: https://github.com/spotify/voyager
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
